namespace HyRest.FileTypeMapping;

internal static class FileTypeMappingUtility
{
    internal static FileTypeEntryCollection GetEntries()
    {
        FileTypeEntry[] entries =
        [
            // audio/video
            new((long)FileTypes.AVIMovie, "aif",    "audio/x-aiff"),
            new((long)FileTypes.AVIMovie, "aifc",   "audio/x-aiff"),
            new((long)FileTypes.AVIMovie, "aiff",   "audio/x-aiff"),
            new((long)FileTypes.AVIMovie, "asf",    "video/x-ms-asf"),
            new((long)FileTypes.AVIMovie, "asx",    "video/x-ms-asf"),
            new((long)FileTypes.AVIMovie, "au",     "audio/basic"),
            new((long)FileTypes.AVIMovie, "avi",    "video/x-msvideo"),
            new((long)FileTypes.AVIMovie, "ivf",    "video/x-ivf"),
            new((long)FileTypes.AVIMovie, "m1v",    "video/mpeg"),
            new((long)FileTypes.AVIMovie, "m3u",    "audio/x-mpegurl"),
            new((long)FileTypes.AVIMovie, "mid",    "audio/midi"),
            new((long)FileTypes.AVIMovie, "midi",   "audio/midi"),
            new((long)FileTypes.AVIMovie, "mov",    "video/quicktime"),
            new((long)FileTypes.AVIMovie, "movie",  "video/x-sgi-movie"),
            new((long)FileTypes.AVIMovie, "mp2",    "audio/mpeg"),
            new((long)FileTypes.AVIMovie, "mp2v",   "audio/mpeg"),
            new((long)FileTypes.AVIMovie, "mp3",    "audio/mpeg"),
            new((long)FileTypes.AVIMovie, "mp4",    "video/mp4"),
            new((long)FileTypes.AVIMovie, "mp4v",   "video/mp4v-es"),
            new((long)FileTypes.AVIMovie, "mpa",    "audio/mpeg"),
            new((long)FileTypes.AVIMovie, "mpe",    "video/mpeg"),
            new((long)FileTypes.AVIMovie, "mpeg",   "video/mpeg"),
            new((long)FileTypes.AVIMovie, "mpg",    "video/mpeg"),
            new((long)FileTypes.AVIMovie, "mpr",    "audio/mpeg"),
            new((long)FileTypes.AVIMovie, "mpv2",   "audio/mpeg"),
            new((long)FileTypes.AVIMovie, "qt",     "video/quicktime"),
            new((long)FileTypes.AVIMovie, "rmi",    "audio/midi"),
            new((long)FileTypes.AVIMovie, "snd",    "audio/basic"),
            new((long)FileTypes.WAVAudio, "wav",    "audio/wav"),
            new((long)FileTypes.WAVAudio, "wave",   "audio/wav"),
            new((long)FileTypes.AVIMovie, "wax",    "audio/x-ms-wax"),
            new((long)FileTypes.AVIMovie, "wm",     "video/x-ms-wm"),
            new((long)FileTypes.AVIMovie, "wma",    "audio/x-ms-wma"),
            new((long)FileTypes.AVIMovie, "wmv",    "video/x-ms-wmv"),
            new((long)FileTypes.AVIMovie, "wmx",    "video/x-ms-wmx"),
            new((long)FileTypes.AVIMovie, "wvx",    "video/x-ms-wvx"),
            // image
            new((long)FileTypes.Image, "bmp",   "image/bmp"),
            new((long)FileTypes.Image, "dcx",   "image/dcx"),
            new((long)FileTypes.Image, "dib",   "image/bmp"),
            new((long)FileTypes.Image, "ico",   "image/vnd.microsoft.icon"),
            new((long)FileTypes.Image, "img",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "jbg",   "image/jpeg"),
            new((long)FileTypes.Image, "jfif",  "image/jpeg"),
            new((long)FileTypes.Image, "jfx",   "image/jpeg"),
            new((long)FileTypes.Image, "jpe",   "image/jpeg"),
            new((long)FileTypes.Image, "jpeg",  "image/jpeg"),
            new((long)FileTypes.Image, "jpg",   "image/jpeg"),
            new((long)FileTypes.Image, "gfi",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gfx",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gif",   "image/gif"),
            new((long)FileTypes.Image, "gim",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gix",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gna",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gnx",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gwx",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "gwz",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "pct",   "image/pict"),
            new((long)FileTypes.Image, "pic",   "image/pict"),
            new((long)FileTypes.Image, "pict",  "image/pict"),
            new((long)FileTypes.Image, "png",   "image/png"),
            new((long)FileTypes.Image, "pnt",   "image/x-macpaint"),
            new((long)FileTypes.Image, "pntg",  "image/x-macpaint"),
            new((long)FileTypes.Image, "psd",   "image/psd"),
            new((long)FileTypes.Image, "svg",   "image/svg+xml"),
            new((long)FileTypes.Image, "svgz",  "image/svg+xml"),
            new((long)FileTypes.Image, "tif",   "image/tiff"),
            new((long)FileTypes.Image, "tiff",  "image/tiff"),
            new((long)FileTypes.Image, "xbm",   "image/x-xbitmap"),
            new((long)FileTypes.Image, "wif",   "image/vnd.onbase"),
            new((long)FileTypes.Image, "xif",   "image/tiff"),
            // Word
            new((long)FileTypes.MsWord, "doc",      "application/msword"),
            new((long)FileTypes.MsWord, "dot",      "application/msword"),
            new((long)FileTypes.MsWord, "docx",     "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
            new((long)FileTypes.MsWord, "dotx",     "application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
            new((long)FileTypes.MsWord, "docm",     "application/vnd.ms-word.document.macroEnabled.12"),
            new((long)FileTypes.MsWord, "dotm",     "application/vnd.ms-word.template.macroEnabled.12"),
            new((long)FileTypes.MsWord, "dochtml",  "application/vnd.ms-word.template.macroEnabled.12"),
            new((long)FileTypes.MsWord, "odt",      "application/vnd.oasis.opendocument.text"),
            // Excel
            new((long)FileTypes.MsExcel, "csv",     "text/csv"),
            new((long)FileTypes.MsExcel, "dif",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "slk",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xla",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xlam",    "application/vnd.ms-excel.addin.macroEnabled.12"),
            new((long)FileTypes.MsExcel, "xlb",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xlc",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xld",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xlk",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xll",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xlm",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xls",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xlsb",    "application/vnd.ms-excel.sheet.binary.macroEnabled.12"),
            new((long)FileTypes.MsExcel, "xlshtml", "application/vnd.ms-excel.sheet.macroEnabled.12"),
            new((long)FileTypes.MsExcel, "xlsm",    "application/vnd.ms-excel.sheet.macroEnabled.12"),
            new((long)FileTypes.MsExcel, "xlsx",    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            new((long)FileTypes.MsExcel, "xlt",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xltm",    "application/vnd.ms-excel.template.macroEnabled.12"),
            new((long)FileTypes.MsExcel, "xltx",    "application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
            new((long)FileTypes.MsExcel, "xlv",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "xlw",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "wbk",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "wiz",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "wll",     "application/vnd.ms-excel"),
            new((long)FileTypes.MsExcel, "ods",     "application/vnd.oasis.opendocument.spreadsheet"),
            // PowerPoint
            new((long)FileTypes.MsPowerPoint, "pot",      "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "pothtml",  "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "potm",     "application/vnd.ms-powerpoint.template.macroEnabled.12"),
            new((long)FileTypes.MsPowerPoint, "potx",     "application/vnd.openxmlformats-officedocument.presentationml.template"),
            new((long)FileTypes.MsPowerPoint, "ppa",      "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "ppam",     "application/vnd.ms-powerpoint.addin.macroEnabled.12"),
            new((long)FileTypes.MsPowerPoint, "pps",      "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "ppsm",     "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"),
            new((long)FileTypes.MsPowerPoint, "ppsx",     "application/vnd.openxmlformats-officedocument.presentationml.slideshow"),
            new((long)FileTypes.MsPowerPoint, "ppt",      "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "ppthtml",  "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "pptm",     "application/vnd.ms-powerpoint.presentation.macroEnabled.12"),
            new((long)FileTypes.MsPowerPoint, "pptx",     "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
            new((long)FileTypes.MsPowerPoint, "pwz",      "application/vnd.ms-powerpoint"),
            new((long)FileTypes.MsPowerPoint, "sldm",     "application/vnd.ms-powerpoint.slide.macroenabled.12"),
            new((long)FileTypes.MsPowerPoint, "sldx",     "application/vnd.openxmlformats-officedocument.presentationml.slide"),
            new((long)FileTypes.MsPowerPoint, "odp",      "application/vnd.oasis.opendocument.presentation"),
            // Outlook, RTF
            new((long)FileTypes.MsOutlook, "msg", "application/x-hsi-msoutlook"),
            new((long)FileTypes.Rtf, "rtf", "application/rtf"),
            new((long)FileTypes.Rtf, "rpt", "application/rtf"),
            // Executable
            new((long)FileTypes.Executable, "dll", "application/x-msdownload"),
            new((long)FileTypes.Executable, "exe", "application/x-msdownload"),
            new((long)FileTypes.Executable, "obd", "application/vnd.ms-binder"),
            new((long)FileTypes.Executable, "obt", "application/vnd.ms-binder"),
            new((long)FileTypes.Executable, "obz", "application/vnd.ms-binder"),
            // HTML / web
            new((long)FileTypes.LotusNotes, "dxl",   "text/xml"),
            new((long)FileTypes.HTML, "htm",    "text/html"),
            new((long)FileTypes.HTML, "html",   "text/html"),
            new((long)FileTypes.HTML, "htt",    "text/html"),
            new((long)FileTypes.HTML, "htw",    "text/html"),
            new((long)FileTypes.HTML, "htx",    "text/html"),
            new((long)FileTypes.HTML, "mht",    "message/rfc822"),
            new((long)FileTypes.HTML, "mhtml",  "message/rfc822"),
            new((long)FileTypes.HTML, "stm",    "text/html"),
            new((long)FileTypes.HTML, "url",    "text/html"),
            // XML
            new((long)FileTypes.XML, "xml", "text/xml"),
            new((long)FileTypes.XML, "xsl", "text/xml"),
            // PDF
            new((long)FileTypes.Pdf, "fdf",  "application/vnd.adobe.fdf"),
            new((long)FileTypes.Pdf, "pdf",  "application/pdf"),
            new((long)FileTypes.Pdf, "pdfa", "application/pdf"),
            new((long)FileTypes.Pdf, "pdfe", "application/pdf"),
            new((long)FileTypes.Pdf, "pdfx", "application/pdf"),
            new((long)FileTypes.Pdf, "pdx",  "application/vnd.adobe.pdx"),
            new((long)FileTypes.Pdf, "rmf",  "application/vnd.adobe.rmf"),
            new((long)FileTypes.Pdf, "xdp",  "application/vnd.adobe.xdp+xml"),
            new((long)FileTypes.Pdf, "xfd",  "application/vnd.adobe.xfd+xml"),
            new((long)FileTypes.Pdf, "xfdf", "application/vnd.adobe.xfdf"),
            // FormDoc
            new((long)FileTypes.FormDoc, "fdd", "application/vnd.formdocs.document"),
            new((long)FileTypes.FormDoc, "fdt", "application/vnd.formdocs.template"),
            // misc
            new((long)FileTypes.Text,                     "txt",  "text/plain"),
            new((long)FileTypes.HPPcl,                    "pcl",  "application/pcl"),
            new((long)FileTypes.AFP,                      "afp",  "application/afp"),
            new((long)FileTypes.EmtexAFPMetacode,         "emt",  "application/afp"),
            new((long)FileTypes.ApproveITElectronicSignature, "cps", "application/vnd.onbase"),
            new((long)FileTypes.DICOMStudy,               "std",  "text/xml"),
            new((long)FileTypes.MeditechArchiveReport,    "mar",  "application/vnd.meditech"),
            new((long)FileTypes.Midmark,                  "car",  "application/vnd.midmark"),
            new((long)FileTypes.CADDocument,              "dwg",  "application/dwg"),
            new((long)FileTypes.ZippedHtmlArchive,        "hzip", "application/zip"),
            new((long)FileTypes.EML,                      "eml",  "message/rfc822"),
            new((long)FileTypes.VNADICOMStudy,            "dcm",  "application/dicom"),
            new((long)FileTypes.ConfigurationPackage,     "expk", "application/zip"),
            new((long)FileTypes.SolutionPackage,          "slpk", "application/zip"),
        ];

        // Display/canonical extension per file type (used by TryGetByFileTypeId)
        FileTypeEntry[] canonical =
        [
            new((long)FileTypes.AFP,               "tiff", "image/tiff"),
            new((long)FileTypes.DJDE,              "tiff", "image/tiff"),
            new((long)FileTypes.HPPcl,             "tiff", "image/tiff"),
            new((long)FileTypes.HPPcl2,            "tiff", "image/tiff"),
            new((long)FileTypes.PclDictionary,     "tiff", "image/tiff"),
            new((long)FileTypes.PCLFilter,         "tiff", "image/tiff"),
            new((long)FileTypes.PclFullSize,       "tiff", "image/tiff"),
            new((long)FileTypes.PclOld,            "tiff", "image/tiff"),
            new((long)FileTypes.PclSelfContain,    "tiff", "image/tiff"),
            new((long)FileTypes.ElectronicForm,    "html", "text/html"),
            new((long)FileTypes.VirtualElectronicForm, "html", "text/html"),
            new((long)FileTypes.HTML,              "html", "text/html"),
            new((long)FileTypes.HTMLUnicode,       "html", "text/html"),
            new((long)FileTypes.HitHighlights,     "html", "text/html"),
            new((long)FileTypes.Verity,            "html", "text/html"),
            new((long)FileTypes.UnityFormHtml,     "html", "text/html"),
            new((long)FileTypes.Text,              "txt",  "text/plain"),
            new((long)FileTypes.Rtf,               "rtf",  "application/rtf"),
            new((long)FileTypes.Executable,        "exe",  "application/x-msdownload"),
            new((long)FileTypes.Midmark,           "car",  "application/vnd.midmark"),
            new((long)FileTypes.MeditechArchiveReport, "mar", "application/vnd.meditech"),
            new((long)FileTypes.MediaStream,       "mp4",  "video/mp4"),
            new((long)FileTypes.GeolocationMapState, "xml", "application/vnd.onbase.mapstate-xml"),
            new((long)FileTypes.ZipCompressionArchive, "zip", "application/x-zip-compressed"),
            new((long)FileTypes.ConfigurationPackage, "zip", "application/x-zip-compressed"),
            new((long)FileTypes.SolutionPackage,   "zip",  "application/x-zip-compressed"),
            new((long)FileTypes.CADDocument,       "dwg",  "application/dwg"),
            new((long)FileTypes.InternalXML,       "xml",  "text/xml"),
            new((long)FileTypes.LotusNotes,        "dxl",  "text/xml"),
            new((long)FileTypes.XML,               "xml",  "text/xml"),
            new((long)FileTypes.DICOMStudy,        "std",  "text/xml"),
            new((long)FileTypes.MsExcel,           "xls",  "application/vnd.ms-excel"),
            new((long)FileTypes.MsOutlook,         "msg",  "application/x-hsi-msoutlook"),
            new((long)FileTypes.MsPowerPoint,      "ppt",  "application/vnd.ms-powerpoint"),
            new((long)FileTypes.ZippedHtmlArchive, "hzip", "application/zip"),
            new((long)FileTypes.MsWord,            "doc",  "application/msword"),
            new((long)FileTypes.Pdf,               "pdf",  "application/pdf"),
            new((long)FileTypes.QTMovie,           "qt",   "video/quicktime"),
            new((long)FileTypes.AVIMovie,          "avi",  "video/x-msvideo"),
            new((long)FileTypes.WAVAudio,          "wav",  "audio/wav"),
            new((long)FileTypes.FormDoc,           "fdd",  "application/vnd.formdocs.document"),
            new((long)FileTypes.FormDocTemplate,   "fdt",  "application/vnd.formdocs.template"),
            new((long)FileTypes.VideoMPEG4,        "mp4",  "video/mp4"),
        ];

        return new FileTypeEntryCollection(entries, canonical);
    }
}